import { randomBytes as secureRandomBytes } from "node:crypto";

/**
 * Settings a fresh deployment generates once. The key and secrets must stay stable afterwards:
 * the key decrypts stored connections and the auth secret keys stored HMACs.
 */
export function renderInitEnv(
	now: Date,
	randomBytes: (size: number) => Buffer = secureRandomBytes,
): string {
	const keyId = `key-${now.toISOString().slice(0, 10).replaceAll("-", "")}`;
	return [
		`# Generated by \`quotum init\` at ${now.toISOString()}. Store these in your secret manager.`,
		"# Keep them stable: stored connections need the key to decrypt, and changing",
		"# QUOTUM_AUTH_SECRET invalidates stored token HMACs. Rotate the key with",
		"# QUOTUM_SECRETS_PREVIOUS_KEY_* and `quotum connections rotate-secrets`.",
		`QUOTUM_SECRETS_KEY_ID=${keyId}`,
		`QUOTUM_SECRETS_KEY_BASE64=${randomBytes(32).toString("base64")}`,
		`QUOTUM_AUTH_SECRET=${randomBytes(32).toString("base64url")}`,
		`BILLING_OPERATOR_API_KEY=${randomBytes(32).toString("base64url")}`,
	].join("\n");
}
